name: Flutter Build Pipeline

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.4"
  GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pubspec_hash: ${{ steps.hash.outputs.pubspec_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate pubspec hash
        id: hash
        run: echo "pubspec_hash=$(sha1sum pubspec.lock | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platforms: [android, web, linux]
          - os: macos-latest
#            platforms: [ios, macos]
            platforms: [macos]
          - os: windows-latest
            platforms: [windows]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: |
            ~/flutter
            ~/.pub-cache
          key: ${{ matrix.os }}-flutter-${{ needs.setup.outputs.pubspec_hash }}

      - name: Setup Flutter
        if: steps.cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Enable Desktop
        if: contains(matrix.platforms, 'linux') || contains(matrix.platforms, 'macos') || contains(matrix.platforms, 'windows')
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            flutter config --enable-linux-desktop
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            flutter config --enable-macos-desktop
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            flutter config --enable-windows-desktop
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup JDK
        if: contains(matrix.platforms, 'android')
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

#      - name: Setup Xcode (iOS)
#        if: contains(matrix.platforms, 'ios')
#        run: |
#          sudo xcode-select -s /Applications/Xcode.app
#          sudo xcodebuild -runFirstLaunch
#
#      - name: Build Android
#        if: contains(matrix.platforms, 'android')
#        run: |
#          flutter build apk --release \
#            --dart-define=APP_ENV=prod \
#            --split-debug-info=debug-info/android
#
#      - name: Build iOS
#        if: contains(matrix.platforms, 'ios')
#        run: |
#          flutter build ipa --release \
#            --dart-define=APP_ENV=prod \
#            --export-options-plist=ios/ExportOptions.plist

      - name: Build Web
        if: contains(matrix.platforms, 'web')
        run: |
          flutter build web --release \
            --dart-define=APP_ENV=prod \
            --base-href /web/

      - name: Build Linux
        if: contains(matrix.platforms, 'linux')
        run: |
          sudo apt-get install -y clang cmake ninja-build
          flutter build linux --release

      - name: Build macOS
        if: contains(matrix.platforms, 'macos')
        run: |
          flutter build macos --release

      - name: Build Windows
        if: contains(matrix.platforms, 'windows')
        run: |
          flutter build windows --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build-${{ github.run_number }}
          path: |
            build/app/outputs/**/*.apk
#            build/ios/**/*.ipa
            build/web/**/*
            build/**/release/**/*
            build/**/*.app
          retention-days: 7

      - name: Create Release
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/**/*.apk
#            build/ios/**/*.ipa
            build/web/**/*
          tag_name: v${{ github.run_number }}
          draft: true
          pre_release: false